name: 下载MusicFree

on:
  schedule:
    - cron: 0 0/4 * * *
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download
        run: |
          curl https://gitee.com/maotoumao/MusicFreePlugins/raw/master/plugins.json > MusicFree.json
          # 更新时间
          sed -i "/MusicFree.json/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./MusicFree.json

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "更新 MusicFree"
          git push origin main
