name: 下载FM

on:
  schedule:
    - cron: 0 9,15,33 * * ? 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download
        run: |
          curl https://raw.iqiq.io/FongMi/CatVodSpider/main/json/config.json > FongMi.json
          # 更新时间
          sed -i "/FongMi.json/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./FongMi.json

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "update src"
          git push origin main
