name: 8oop

on:
  schedule:
    - cron: 0 9,15,22 * * ? 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download from 8oop
        run: |
          curl 8oop > 8oop.json
          # 更新时间
          sed -i "/8oop.json/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./8oop.json

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "update src"
          git push origin main
