name: 更新iptvindex

on:
  schedule:
    - cron: 0 0/4 * * *
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 更新 FongMi.json
        run: |
          curl https://iptvindex.com/tv.txt > tv/tv.txt
          # 更新时间
          sed -i "/tv.txt/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./tv/tv.txt

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "更新 iptvindex"
          git push origin main
